version: 2
jobs:
  build:
    docker:
      - image: jacekelgda/pr-troll:fe6dd32124b6615a823ee7c74e0fb8564ddde6b5
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn eslint
      - run: yarn test
      - run: pr-troll
